name: lint

on: [push, pull_request]

jobs:
  ruff-black-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
      - name: Install dependencies
        run: |
          python -m pip install .
          pip install -r dev-requirements.txt
      - name: black check
        run: black --check --preview .
      - name: isort check
        run: isort --profile black --check .
